### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Index Dogs
GET http://localhost:3000/dogs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5ODA1MjJ9.9sU2Tr4mvLyYh4VqHo4Dfy_2lEmy9Pqy3fMnZLAe-kA

### Show Dog
GET http://localhost:3000/dogs/5

### Create Dog

POST http://localhost:3000/dogs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5NzY3MDN9.e5__yRWkfsiTuJWrzo2wIYHIbvrhHD9FmlDDPar-ACg
Content-Type: application/json

{
    "name": "Emma",
    "age": 13,
    "breed": "Pug"
}

### Update Dog

PATCH http://localhost:3000/dogs/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5ODA1MjJ9.9sU2Tr4mvLyYh4VqHo4Dfy_2lEmy9Pqy3fMnZLAe-kA
Content-Type: application/json

{
    "name": "Emma",
    "age": 101,
    "breed": "Pug God"
}

### Delete Dog

DELETE http://localhost:3000/dogs/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5ODA1MjJ9.9sU2Tr4mvLyYh4VqHo4Dfy_2lEmy9Pqy3fMnZLAe-kA